### PR TITLE
[fix] update missing item in activity 4

### PR DESCRIPTION
**Pull request by Remi-Gau**
Quick fix:
- email item is already in activity 3
- float item was not presented in activity 4

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Side note that might be more appropriate on the reproschem-py repo: Shouldn't validation also ensure that the items listed in an activity actually "exist"? 
Other wise most apps that implement the schema will just hang eternally.

**Comment by satra** [comment]
> Shouldn't validation also ensure that the items listed in an activity actually "exist"?

Good question. Validation checks the graph presently not content derived from a location. So it checks that the pointer acts as a uri not a url. Indeed would be good to test that the uri are also url. That should be an easy addition given the triples.

**Comment by Remi-Gau** [comment]
will open an issue on reproschema-py at least a reminder

**Comment by Remi-Gau** [comment]
Closing as this is now obsolete

**Pull request closed without merging**
