### PR TITLE
[ENH] add text area item

### PR DESCRIPTION
**Pull request by Remi-Gau**
add a text area item as mentioned in https://github.com/ReproNim/reproschema-ui/issues/297

### CODE REVIEW

**Comment by Remi-Gau** [comment]
The change can be viewed [here](https://www.repronim.org/reproschema-ui/#/activities/0?url=https%3A%2F%2Fraw.githubusercontent.com%2FRemi-Gau%2Fdemo-protocol%2FtextArea%2Factivities%2FActivity3%2FActivity3_schema)

**Comment by satra** [comment]
@danielmlow - aren't you using a text area for the journaling inputs in the current study? or is that a single line? just checking to make sure @Remi-Gau 's PR is not redundant with something that's already there.

**Comment by danielmlow** [comment]
@satra yes. It creates a larger text box:
image

Here's an example of the code: https://github.com/mentalwellbeing/WellBeingStudy_daily/blob/54ddc1470e2a5a9101211cac10ab623a91e3a4fc/activities/daily_activity/items/journaling_1#L11

**Comment by satra** [comment]
@Remi-Gau - given what @danielmlow just posted, i think this may already exist and may just need documentation?

**Comment by satra** [comment]
nevermind, i was being stupid.

**Pull request merged**
